#!/usr/bin/env python3
"""Manage repo-map.toml files and generated Cargo local dependency overrides."""

from __future__ import annotations

import argparse
import os
import shutil
import sys
from dataclasses import dataclass
from pathlib import Path

try:
    import tomllib
except ModuleNotFoundError:  # pragma: no cover - Python < 3.11 fallback
    print("Python 3.11+ is required for tomllib", file=sys.stderr)
    sys.exit(2)


DEFAULT_CARGO_CONFIG = ".cargo/config.toml"


@dataclass(frozen=True)
class RepoMap:
    path: Path
    data: dict

    @property
    def root(self) -> Path:
        return self.path.parent


def _find_map_path(explicit_map: str | None, explicit_root: str | None) -> Path:
    if explicit_map:
        return Path(explicit_map).expanduser().resolve()

    search_root = Path(explicit_root).expanduser().resolve() if explicit_root else Path.cwd().resolve()
    candidates = [search_root, *search_root.parents]

    script_root = Path(__file__).resolve().parent
    candidates.extend([script_root, *script_root.parents])

    seen: set[Path] = set()
    for candidate in candidates:
        if candidate in seen:
            continue
        seen.add(candidate)
        map_path = candidate / "repo-map.toml"
        if map_path.exists():
            return map_path

    return search_root / "repo-map.toml"


def _load_map(args: argparse.Namespace) -> RepoMap:
    path = _find_map_path(args.map, args.root)
    if not path.exists():
        raise FileNotFoundError(f"repo map not found: {path}")
    with path.open("rb") as handle:
        return RepoMap(path=path, data=tomllib.load(handle))


def _repo_root(repo_map: RepoMap, repo: dict) -> Path:
    if "absolute" in repo:
        return Path(os.path.expandvars(repo["absolute"])).expanduser().resolve()
    if "relative" not in repo:
        raise ValueError("repo entry must define either 'relative' or 'absolute'")
    return (repo_map.root / repo["relative"]).resolve()


def _display_path(repo_map: RepoMap, path: Path) -> str:
    try:
        return os.path.relpath(path, repo_map.root)
    except ValueError:
        return str(path)


def _toml_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _cargo_patch_rows(repo_map: RepoMap) -> list[tuple[str, str, Path]]:
    rows: list[tuple[str, str, Path]] = []
    for _name, repo in sorted(repo_map.data.get("repos", {}).items()):
        repo_root = _repo_root(repo_map, repo)
        for patch in repo.get("cargo_patches", []):
            rows.append(
                (
                    patch["source"],
                    patch["package"],
                    (repo_root / patch.get("path", ".")).resolve(),
                )
            )
    return rows


def render_cargo_config(repo_map: RepoMap) -> str:
    by_source: dict[str, list[tuple[str, Path]]] = {}
    for source, package, path in _cargo_patch_rows(repo_map):
        by_source.setdefault(source, []).append((package, path))

    lines = [
        "# Generated by repo_map.py from repo-map.toml.",
        "# Do not edit by hand; update repo-map.toml and regenerate.",
        "",
    ]
    for source in sorted(by_source):
        lines.append(f'[patch."{source}"]')
        for package, path in sorted(by_source[source]):
            lines.append(f"{package} = {{ path = {_toml_string(_display_path(repo_map, path))} }}")
        lines.append("")
    return "\n".join(lines)


def cargo_config_path(repo_map: RepoMap) -> Path:
    rel = repo_map.data.get("standard", {}).get("cargo_config", DEFAULT_CARGO_CONFIG)
    return (repo_map.root / rel).resolve()


def write_cargo_config(args: argparse.Namespace) -> int:
    repo_map = _load_map(args)
    patches = _cargo_patch_rows(repo_map)
    if not patches and not args.allow_empty:
        print("repo-map has no cargo_patches; use --allow-empty to write an empty config", file=sys.stderr)
        return 1

    path = cargo_config_path(repo_map)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_cargo_config(repo_map), encoding="utf-8")
    print(f"wrote {_display_path(repo_map, path)}")
    return 0


def check(args: argparse.Namespace) -> int:
    repo_map = _load_map(args)
    errors: list[str] = []

    for name, repo in sorted(repo_map.data.get("repos", {}).items()):
        root = _repo_root(repo_map, repo)
        if not root.exists():
            errors.append(f"missing repo {name}: {_display_path(repo_map, root)}")
        for patch in repo.get("cargo_patches", []):
            patch_path = root / patch.get("path", ".")
            if not patch_path.exists():
                errors.append(
                    f"missing cargo patch path {name}.{patch['package']}: "
                    f"{_display_path(repo_map, patch_path)}"
                )

    if _cargo_patch_rows(repo_map):
        expected = render_cargo_config(repo_map)
        config_path = cargo_config_path(repo_map)
        if not config_path.exists():
            errors.append(f"missing generated Cargo config: {_display_path(repo_map, config_path)}")
        elif config_path.read_text(encoding="utf-8") != expected:
            errors.append("stale generated Cargo config: run 'python scripts\\repo_map.py write-cargo-config'")

    if errors:
        for error in errors:
            print(f"ERROR: {error}", file=sys.stderr)
        return 1
    print("repo-map check: pass")
    return 0


def list_repos(args: argparse.Namespace) -> int:
    repo_map = _load_map(args)
    for name, repo in sorted(repo_map.data.get("repos", {}).items()):
        root = _repo_root(repo_map, repo)
        status = "present" if root.exists() else "missing"
        clone_url = repo.get("clone_url", repo.get("canonical", ""))
        branch = repo.get("branch")
        suffix = f" ({branch})" if branch else ""
        print(f"{name}: {status} {_display_path(repo_map, root)} <- {clone_url}{suffix}")
    return 0


def clone_commands(args: argparse.Namespace) -> int:
    repo_map = _load_map(args)
    for _name, repo in sorted(repo_map.data.get("repos", {}).items()):
        root = _repo_root(repo_map, repo)
        if root.exists():
            continue
        clone_url = repo.get("clone_url")
        if not clone_url:
            continue
        branch = repo.get("branch")
        branch_arg = f" --branch {branch}" if branch else ""
        print(f"git clone{branch_arg} {clone_url} {_display_path(repo_map, root)}")
    return 0


def install(args: argparse.Namespace) -> int:
    target = Path(args.target).expanduser().resolve()
    if not target.exists():
        raise FileNotFoundError(f"target repo does not exist: {target}")

    tools_dir = target / "tools"
    tools_dir.mkdir(parents=True, exist_ok=True)
    shutil.copy2(Path(__file__).resolve(), tools_dir / "repo_map.py")

    if not (target / "repo-map.toml").exists():
        template = Path(__file__).resolve().parents[1] / "templates" / "repo-map.toml"
        if template.exists():
            shutil.copy2(template, target / "repo-map.toml")

    print(f"installed tools\\repo_map.py in {target}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--map", help="path to repo-map.toml")
    parser.add_argument("--root", help="root used to find repo-map.toml when --map is omitted")
    sub = parser.add_subparsers(dest="command", required=True)

    write_parser = sub.add_parser(
        "write-cargo-config",
        help="generate .cargo/config.toml from repo-map.toml cargo_patches",
    )
    write_parser.add_argument("--allow-empty", action="store_true", help="write config even with no cargo_patches")
    write_parser.set_defaults(func=write_cargo_config)

    sub.add_parser("check", help="validate mapped paths and generated Cargo config").set_defaults(func=check)
    sub.add_parser("list", help="list mapped repositories and local status").set_defaults(func=list_repos)
    sub.add_parser("clone-commands", help="print git clone commands for missing mapped repos").set_defaults(
        func=clone_commands
    )

    install_parser = sub.add_parser("install", help="copy repo_map.py and template repo-map.toml into a repo")
    install_parser.add_argument("target", help="target repository root")
    install_parser.set_defaults(func=install)

    args = parser.parse_args()
    try:
        return args.func(args)
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
