const $=s=>document.querySelector(s), worker=new Worker('./worker.js',{type:'module'});
let ready=false,request=0,timer,result,svgUrl;
for(const [i,name]of ['West A','West B','East A','East B'].entries()){const label=document.createElement('label');label.htmlFor=`unit-${i}`;label.textContent=name;const select=document.createElement('select');select.id=label.htmlFor;select.disabled=true;for(const [value,text]of [['0','Zone A'],['1','Zone B']]){const option=new Option(text,value);select.add(option);}select.value=i<2?'0':'1';select.onchange=calculate;$('#assignments').append(label,select);}
function calculate(){request++;clearTimeout(timer);$('#west-value').textContent=$('#west').value;$('#east-value').textContent=$('#east').value;if(!ready)return;$('#export').disabled=true;$('#status').textContent='Evaluating…';timer=setTimeout(()=>worker.postMessage({id:request,assignment:[0,1,2,3].map(i=>Number($(`#unit-${i}`).value)),west:Number($('#west').value),east:Number($('#east').value),daylight:Number($('#daylight').value)}),80);}
function fail(message){$('#status').textContent=message;$('#export').disabled=true;$('#map').hidden=true;$('#verdict').textContent='Could not evaluate';}
worker.onerror=()=>fail('Evaluator could not load. Reload to retry or read the source.');
worker.onmessage=({data})=>{if(data.type==='ready'){ready=true;document.querySelectorAll('input,select,button').forEach(e=>e.disabled=false);calculate();return;}if(data.id!==undefined&&data.id!==request)return;if(data.type==='error'){fail(data.message);return;}result=data.result;const r=result.report,f=result.fit;$('#error').textContent=(Number($('#daylight').value)===0?f.current_weighted_mean_standard_error_minutes:f.current_weighted_mean_dst_error_minutes).toFixed(2);$('#edges').textContent=r.boundary_edges;$('#moved').textContent=r.moved_population;$('#verdict').textContent=r.all_zones_connected?'Zones connected':'Disconnected zones';$('#baseline').textContent=`Standard-clock baseline: ${result.baseline.weighted_mean_absolute_error_minutes.toFixed(2)} minutes mean error. Standard-clock experiment: ${r.weighted_mean_absolute_error_minutes.toFixed(2)} minutes.`;$('#status').textContent=`4 synthetic units · ${data.ms.toFixed(1)} ms · processing stays on your device`;if(svgUrl)URL.revokeObjectURL(svgUrl);svgUrl=URL.createObjectURL(new Blob([result.svg],{type:'image/svg+xml'}));$('#map').src=svgUrl;$('#map').hidden=false;$('#scores').replaceChildren();for(const unit of f.unit_scores){const row=document.createElement('tr');for(const value of [unit.unit_name,unit.population,unit.current_standard_error_minutes.toFixed(1),unit.current_dst_error_minutes.toFixed(1)]){const cell=document.createElement('td');cell.textContent=value;row.append(cell);}$('#scores').append(row);}$('#export').disabled=false;};
for(const id of ['west','east'])$(`#${id}`).oninput=calculate;$('#daylight').onchange=calculate;
$('#reset').onclick=()=>{$('#west').value='-360';$('#east').value='-300';$('#daylight').value='0';for(let i=0;i<4;i++)$(`#unit-${i}`).value=i<2?'0':'1';history.replaceState(null,'',location.pathname);calculate();};
$('#share').onclick=async()=>{const url=new URL(location.href);url.search='';for(const id of ['west','east','daylight'])url.searchParams.set(id,$(`#${id}`).value);url.searchParams.set('units',[0,1,2,3].map(i=>$(`#unit-${i}`).value).join(''));history.replaceState(null,'',url);try{await navigator.clipboard.writeText(url.href);}catch{}$('#status').textContent='Experiment link is in the address bar.';};
$('#export').onclick=()=>{if(!result)return;const url=URL.createObjectURL(new Blob([JSON.stringify(result,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download='zones-synthetic-comparison.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
const params=new URLSearchParams(location.search);for(const id of ['west','east']){const n=Number(params.get(id));if(params.has(id)&&Number.isInteger(n)&&n>=-720&&n<=840&&n%15===0)$(`#${id}`).value=n;}if(['0','60'].includes(params.get('daylight')))$('#daylight').value=params.get('daylight');if(/^[01]{4}$/.test(params.get('units')||''))for(let i=0;i<4;i++)$(`#unit-${i}`).value=params.get('units')[i];worker.postMessage({type:'init'});
